/**
 * Medical specialties constants for the client application
 * Keep in sync with SekondlyApp/src/types/shared.ts
 */

export const MEDICAL_SPECIALTIES = [
  "Addiction Psychiatry Fellowship",
  "Adult & Pediatric Orthopedic Spinal Surgery Fellowship",
  "Adult Allergy & Immunology Fellowship",
  "Adult Critical Care",
  "Adult Critical Care Fellowship",
  "Adult Echocardiography",
  "Adult Endocrinology & Metabolism Fellowship",
  "Adult Gastroenterology Fellowship",
  "Adult Hematology Fellowship",
  "Adult Interventional Cardiology Fellowship",
  "Adult Orthopedic Reconstructive surgery Fellowship",
  "Adult Psychosomatic Medicine Fellowship",
  "Adult Stem Cell Transplantation Fellowship",
  "Adults Cardiology Fellowship",
  "Adults Infectious Diseases",
  "Adults Respiratory Medicine Fellowship",
  "Advanced Cardiac lmaging Fellowship",
  "Advanced General Pediatrics Fellowship",
  "Anatomic Pathology",
  "Anesthesia",
  "Arthroscopy and Orthopedic Sport Injuries Fellowship",
  "Body Imaging & non-vascular intervention",
  "Bone and Soft Tissue Pathology Fellowship",
  "Breast and Gynecologic Pathology Fellowship",
  "Breast Imaging Fellowship",
  "Burn Critical Care Fellowship",
  "Cardiac Anesthesia",
  "Cardiac Critical Care Fellowship",
  "Cardiac Electrophysiology & Pacing Fellowship",
  "Cardiac Surgery",
  "Cardiothoracic Radiology Fellowship",
  "Child And Adolescent Psychiatry Fellowship",
  "Clinical Genetics & Metabolic Disorders Fellowship",
  "Clinical Neurophysiology Fellowship",
  "Clinician Investigator",
  "Colon and Rectal Surgery Fellowship",
  "Comprehensive Ophthalmology Fellowship",
  "Cornea/ External Disease Fellowship",
  "Dermatology",
  "Developmental and Behavioral Pediatric Fellowship",
  "Diabetes Fellowship",
  "Diagnostic Neuroradiology Fellowship",
  "Diagnostic Radiology",
  "Emergency Medical Services and Disaster Medicine Fellowship",
  "Emergency Medicine",
  "Emergency Medicine Diploma",
  "Endocrine & Breast Surgery Fellowship",
  "Epilepsy & Electroencephalography",
  "Family Medicine",
  "Forensic Medicine",
  "General Surgery",
  "Geriatric Medicine Fellowship",
  "Glaucoma",
  "Gynecological Oncology Fellowship",
  "Head & Neck Oncology Surgery Fellowship",
  "Hematopathology",
  "Hepatobiliary pancreatic surgery Fellowship",
  "Home Health Care Physicians Diploma",
  "Hospitalist Medicine Fellowship",
  "Infertility Andrology Fellowship",
  "Internal Medicine",
  "Interventional Nephrology",
  "Interventional Neuro-Radiology",
  "Life Style Medicine",
  "Lymphoma and Plasma Cell Disorders Fellowship",
  "Maternal Fetal Medicine Fellowship",
  "Medical Oncology Fellowship",
  "Medical Retina & Uveitis Fellowship",
  "Medical Specialty",
  "Minimat lnvasive Upper Gl and Bariatri Surgery Fellowship",
  "Movement Disorder Fellowship",
  "Musculoskeletal Oncology Fellowship",
  "Musculoskeletal Radiology Fellowship",
  "Nephropathologist Renal transplant Pathology Fellowship",
  "Nero-Ophthalmology",
  "Neurological Physiotherapy",
  "Neurology",
  "Neurosurgery",
  "Neurosurgery Skull Base Fellowship",
  "Neurourology Fellowship",
  "Nuclear Medicine Fellowship",
  "Obesity Medicine Fellowship",
  "Obstetric Anesthesiology Fellowship",
  "Obstetrics & Gynecology",
  "Oculoplastic and Orbit Surgery Fellowship",
  "Ophthalmology",
  "Orthopedic Surgery",
  "Orthopedic Trauma Surgery Fellowship",
  "Otology, Neurotology and Lateral Skull-Base Surgery",
  "Otorhinolaryngology Head and Neck Surgery",
  "Pain Medicine Fellowship",
  "Palliative Care Medicine",
  "Pediatric Allergy And Immunology",
  "Pediatric Anesthesia",
  "Pediatric Cardiac Critical Care Fellowship",
  "Pediatric Cardiology Fellowship",
  "Pediatric Diagnostic Radiology",
  "Pediatric Echocardiography Fellowship",
  "Pediatric Endocrinology and Metabolism Fellowship",
  "Pediatric Gastroenterology and Nutrition Fellowship",
  "Pediatric Hematology & Oncology Fellowship",
  "Pediatric Intensive Care Fellowship",
  "Pediatric Nephrology Fellowship",
  "Pediatric Neurology",
  "Pediatric Neurosurgery Fellowship",
  "Pediatric Ophthalmology and Strabismus Fellowship",
  "Pediatric Orthopedic Surgery Fellowship",
  "Pediatric Otolaryngology",
  "Pediatric Respiratory Medicine Fellowship",
  "Pediatric Rheumatology Fellowship",
  "Pediatric Stem Cell Transplantation Fellowship",
  "Pediatric Surgery",
  "Pediatric Surgery Fellowship",
  "Pediatric Urology Fellowship",
  "Pediatrics",
  "Pediatrics Diploma",
  "Pediatrics Emergency Medicine Fellowship",
  "Pediatrics Infectious Diseases Fellowship",
  "Perinatal Neonatal Medicine Fellowship",
  "Physical Medicine and Rehabilitation",
  "Plastic and Reconstructive Surgery",
  "Preventive Medicine",
  "Primary Mental Health Care Fellowship",
  "Psychiatry",
  "Radiation Oncology",
  "Reconstructive Microvascular Surgery Fellowship",
  "Regional Anesthesia",
  "Renal Transplant Fellowship",
  "Renal Transplant Surgery Fellowship",
  "Reproductive Medicine & Surgery Fellowship",
  "Rheumatology Fellowship",
  "Rhinology, Sinus and Skull-Base Surgery Fellowship",
  "Saudi Fellowship Program in Nephrology",
  "Sleep Medicine Fellowship",
  "Therapeutic Endoscopy Fellowship",
  "Thoracic Surgery Fellowship",
  "Transplant Hepatology Fellowship",
  "Trauma and Acute Surgery Fellowship",
  "Urethral Reconstruction Fellowship",
  "Urogynecologist and Pelvic Reconstructive Surgery",
  "Urology",
  "vascular and Interventional radiology Fellowship",
  "Vascular Neurology (Stroke)",
  "Vascular Surgery Fellowship",
  "Vitreoretinal Surgery Fellowship",
  "Women's Health Fellowship",
] as const;

export type Specialty = typeof MEDICAL_SPECIALTIES[number];

/**
 * Board certifications for medical professionals
 * Maps to MEDICAL_SPECIALTIES for consistency
 */
export const BOARD_CERTIFICATIONS = MEDICAL_SPECIALTIES;

export type BoardCertification = typeof BOARD_CERTIFICATIONS[number];

/**
 * Medical levels for user classification
 * Keep in sync with SekondlyApp/src/types/shared.ts
 */
export const MEDICAL_LEVELS = [
  "Medical Student",
  "Intern",
  "Resident",
  "Specialist",
  "Consultant"
] as const;

export type MedicalLevel = typeof MEDICAL_LEVELS[number];
